
channel.parallel=8

remote.host=192.168.5.150
remote.port=22
remote.user=dhrg
remote.password=p4R7LrU3E

dir.local=D:/wrk/_DEV/nexios-fe/deploy/dev/www/dev
dir.remote=/usr/local/nexios/www/dev/scptest

dir1.local=D:/wrk/_DEV/nexios-fe/deploy/dev/www/dev
dir1.remote=/usr/local/nexios/www/dev/scptest
