#!/usr/bin/env bun
/**
 * Produces a REAL merge report for the review page, so the visual check renders data the merge engine
 * actually decided rather than a fixture somebody typed (plan step 4.2).
 *
 * It drives the public API the module's own tests use — `MergeBatch.using(resolver).add(path, base,
 * branch1, branch2)` then `MergeReportWriter.write` — over three files chosen to exercise three shapes:
 * an import both branches added (AUTO), a type change (REVIEW), and a method signature that only a
 * human can decide (MANUAL).
 *
 * The harness is a Java source file written to `.tmp/` and run with the JDK's single-file source
 * launcher: it is scratch by nature (it exists for one run and changes with the sample), and `.tmp/`
 * is where scratch goes — not `target/`, which `mvn clean` deletes, and not `scripts/`, which is for
 * things a reader needs (AGENTS.md § 2).
 *
 * Usage:
 *   bun run scripts/merge-report/sample-report.js [--out <report.json>]
 *
 * Default output: <repo>/.tmp/merge-review/merge-report.json
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { delimiter, envWith, repoRoot, resolveJdk25, resolveMaven, run } from '../../../scripts/lib/toolchain.js'
import { moduleClasspath } from './classpath.js'

const here = dirname(fileURLToPath(import.meta.url))
const mergeJavaRoot = resolve(here, '../..')
const root = repoRoot()

const args = process.argv.slice(2)
const valueOf = (flag, fallback) => {
  const index = args.indexOf(flag)
  return index >= 0 && index + 1 < args.length ? args[index + 1] : fallback
}
const scratch = join(root, '.tmp', 'merge-review')
const out = resolve(valueOf('--out', join(scratch, 'merge-report.json')))
mkdirSync(scratch, { recursive: true })

const jdk = resolveJdk25()
const maven = resolveMaven()
const env = envWith(jdk)

// ── 1. the classpath, from Maven so it cannot drift from the POM ────────────────────────────────────
const resolvedClasspath = moduleClasspath({ moduleRoot: mergeJavaRoot, scratchDir: scratch, maven, env, cwd: root })
console.log(`[sample-report] module classpath ${resolvedClasspath.fromCache ? 'from cache' : 'resolved'} (keyed by the POM)`)
const dependencies = resolvedClasspath.entries

// ── 2. the harness: real three-way inputs through the public API ────────────────────────────────────
const harness = join(scratch, 'RenderSampleReport.java')
writeFileSync(
  harness,
  `import com.codebuddy.merge.MergeBatch;
import com.codebuddy.merge.MergeConflictResolver;
import com.codebuddy.merge.MergeReportWriter;
import com.codebuddy.merge.TypeContext;

import java.nio.file.Path;

/**
 * Generated by scripts/merge-report/sample-report.js — scratch, not source. It exists to hand the
 * review page a report the engine really produced.
 */
public final class RenderSampleReport {

    public static void main(String[] args) throws Exception {
        MergeConflictResolver resolver = new MergeConflictResolver.Builder()
                .setBranchName("feature-payments")
                .setHistoryPath(Path.of(args[1]))
                // The default resolver set includes OverloadAddConflictResolver, whose classpath is a HARD
                // requirement: comparing resolved parameter types has no weaker form, so a set containing it
                // cannot be built without a context (README, "Status"). The runtime classpath is the JDK, which
                // is what these samples' types (TreeSet, NavigableSet) resolve against.
                .setTypeContext(TypeContext.withRuntimeClasspath(Path.of(args[2])))
                .build();

        MergeBatch batch = MergeBatch.using(resolver)
                .add("src/main/java/com/example/demo/PaymentProcessor.java", IMPORTS_BASE, IMPORTS_B1, IMPORTS_B2)
                .add("src/main/java/com/example/demo/Ledger.java", LEDGER_BASE, LEDGER_B1, LEDGER_B2)
                .add("src/main/java/com/example/demo/OrderService.java", ORDER_BASE, ORDER_B1, ORDER_B2);

        MergeReportWriter.write(Path.of(args[0]), batch);
        System.out.println("wrote " + args[0]);
    }

    private static final String IMPORTS_BASE = """
            package com.example.demo;

            import java.util.List;

            class PaymentProcessor {
                void process(List<String> ids) {
                    ids.forEach(this::handle);
                }
            }
            """;

    private static final String IMPORTS_B1 = """
            package com.example.demo;

            import java.util.List;
            import java.math.BigDecimal;

            class PaymentProcessor {
                void process(List<String> ids) {
                    ids.forEach(this::handle);
                }
            }
            """;

    private static final String IMPORTS_B2 = """
            package com.example.demo;

            import java.util.List;
            import java.time.Instant;

            class PaymentProcessor {
                void process(List<String> ids) {
                    ids.forEach(this::handle);
                }
            }
            """;

    private static final String LEDGER_BASE = """
            package com.example.demo;

            import java.util.Set;
            import java.util.TreeSet;

            class Ledger {
                private final Set<String> entries = new TreeSet<>();
            }
            """;

    private static final String LEDGER_B1 = """
            package com.example.demo;

            import java.util.TreeSet;

            class Ledger {
                private final TreeSet<String> entries = new TreeSet<>();
            }
            """;

    private static final String LEDGER_B2 = """
            package com.example.demo;

            import java.util.NavigableSet;
            import java.util.TreeSet;

            class Ledger {
                private final NavigableSet<String> entries = new TreeSet<>();
            }
            """;

    private static final String ORDER_BASE = """
            package com.example.demo;

            class OrderService {
                void process(String id) {
                    log.info("processing {}", id);
                }
            }
            """;

    private static final String ORDER_B1 = """
            package com.example.demo;

            class OrderService {
                void process(String id) {
                    log.info("processing {}", id);
                    audit.record(id);
                }
            }
            """;

    private static final String ORDER_B2 = """
            package com.example.demo;

            class OrderService {
                void process(CharSequence id) {
                    log.info("processing {}", id);
                    metrics.count(id);
                }
            }
            """;
}
`,
)

// ── 3. run it: the single-file source launcher, on JDK 25 with the module's classes ─────────────────
const classpath = [join(mergeJavaRoot, 'target', 'classes'), dependencies].filter(Boolean).join(delimiter)
console.log('[sample-report] running the harness on ' + jdk.home)
const harnessRun = run(
  jdk.java,
  ['-cp', classpath, harness, out, join(scratch, 'merge-history', 'feature-payments'), scratch],
  { env, cwd: root },
)
if (harnessRun.status !== 0) {
  console.error(`[sample-report] the harness failed with exit code ${harnessRun.status}`)
  process.exit(harnessRun.status ?? 1)
}

console.log(`[sample-report] report: ${out}`)
console.log('[sample-report] render it:')
console.log(`  cd merge-java/review && bun run src_build/build.js --report ${out} && bun run src_build/screenshot.js`)
