<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>hr.hrg.jcodebuddy</groupId>
        <artifactId>jcodebuddy-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>hipster-ioc-api</artifactId>
    <name>hipster-ioc-api</name>
    <description>Annotations and interfaces for hipster-ioc</description>

    <dependencies>
        <dependency>
            <groupId>hr.hrg.jcodebuddy</groupId>
            <artifactId>hipster-entity-api</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
