#!/usr/bin/env bun
/**
 * Builds the merge-java review page: the report is inlined at build time (so the page opens from
 * `file://` with no server and no fetch — a `fetch()` of a sibling JSON is blocked by CORS on
 * `file://`), then esbuild bundles the JSX against the local jsx6 checkout.
 *
 * Usage:
 *   bun run src_build/build.js [--report <path>] [--out <dir>] [--dev]
 *
 * Defaults: --report <merge-java>/.jcodebuddy/metadata/merge-report.json when it exists, else the
 * committed sample-report.json; --out build/
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { esbDef, jsx6Root, libraryAliases } from './esbDef.js'

const here = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(here, '..')
const repoRoot = resolve(packageRoot, '../..')
const mergeJavaRoot = resolve(packageRoot, '..')

const args = process.argv.slice(2)
const valueOf = (flag, fallback) => {
  const index = args.indexOf(flag)
  return index >= 0 && index + 1 < args.length ? args[index + 1] : fallback
}
const dev = args.includes('--dev')
const outDir = resolve(valueOf('--out', join(packageRoot, 'build')))
const defaultReport = join(mergeJavaRoot, '.jcodebuddy', 'metadata', 'merge-report.json')
const sampleReport = join(packageRoot, 'sample-report.json')
const reportArg = valueOf('--report', null)
const reportPath = resolve(reportArg ?? defaultReport)
const USAGE = 'usage: bun run src_build/build.js [--report <report.json>] [--out <dir>] [--dev]'

let reportSource = reportPath
let reportJson
if (reportArg !== null) {
  // An explicitly named report MUST exist. Falling back to the sample here would render different data
  // than the caller asked for — the one failure a review display must never have — so it is misuse, and
  // it exits like misuse (status 2, with the usage line), which is also the shape the shell test holds.
  try {
    reportJson = readFileSync(reportPath, 'utf8')
  } catch (error) {
    console.error(`[review] cannot read the report given with --report:\n  ${reportPath}\n  ${error.message}`)
    console.error(USAGE)
    process.exit(2)
  }
} else {
  try {
    reportJson = readFileSync(defaultReport, 'utf8')
  } catch {
    reportSource = sampleReport
    reportJson = readFileSync(sampleReport, 'utf8')
  }
}
// Parse here rather than trusting the file: a malformed report must fail the build, not the page.
let report
try {
  report = JSON.parse(reportJson)
} catch (error) {
  console.error(`[review] the report is not valid JSON:\n  ${reportSource}\n  ${error.message}`)
  console.error(USAGE)
  process.exit(2)
}

// The generated module is what the page imports; it lives outside src/ so generated output never
// mixes with source, and the source path travels with it so the page can say where its data is from.
//
// `repoRoot` travels with it too (plan step 4.13, deliverable 2): the exported decisions file records
// the absolute repository root, which is what lets `DecisionRecorder` be run from any working
// directory. The page cannot discover it at view time — a `file://` document has no such notion — and
// the build knows it exactly, so it is written here rather than guessed there.
const generatedDir = join(packageRoot, '.generated')
mkdirSync(generatedDir, { recursive: true })
writeFileSync(
  join(generatedDir, 'report.js'),
  `// @generated by src_build/build.js — do not edit.\n` +
    `export const reportSource = ${JSON.stringify(reportSource)}\n` +
    `export const isSample = ${reportSource === sampleReport}\n` +
    `export const repoRoot = ${JSON.stringify(repoRoot)}\n` +
    `export const report = ${JSON.stringify(report, null, 2)}\n`,
)

const root = jsx6Root(repoRoot)
const aliases = libraryAliases(root)
const esbuildArgs = [
  'esbuild',
  join(packageRoot, 'src', 'index.jsx'),
  `--outfile=${join(outDir, 'review.js')}`,
  '--bundle',
  `--format=${esbDef.format}`,
  `--jsx=${esbDef.jsx}`,
  `--jsx-import-source=${esbDef.jsxImportSource}`,
  `--tsconfig=${join(packageRoot, esbDef.tsconfig)}`,
  '--sourcemap',
  ...Object.entries(esbDef.loader).map(([ext, loader]) => `--loader:${ext}=${loader}`),
  ...Object.entries(aliases).map(([name, entry]) => `--alias:${name}=${entry}`),
  ...(dev ? ['--jsx-dev'] : []),
]

mkdirSync(outDir, { recursive: true })
console.log(`[review] report:  ${reportSource}${reportSource === sampleReport ? '  (sample)' : ''}`)
console.log(`[review] jsx6:    ${root}  (${Object.keys(aliases).length} libs aliased)`)
console.log(`[review] out:     ${outDir}`)

// The CLI with inherited stdio, not the JS API: jsx6's agent-rules note that the JS API spawns a
// piped service, which a confined sandbox denies with EPERM (jsx6/docs/stack/agent-rules.md).
const build = Bun.spawnSync(['bunx', ...esbuildArgs], {
  cwd: packageRoot,
  stdio: ['inherit', 'inherit', 'inherit'],
})
if (build.exitCode !== 0) {
  console.error(`[review] esbuild failed with exit code ${build.exitCode}`)
  process.exit(build.exitCode ?? 1)
}

copyFileSync(join(packageRoot, 'index.html'), join(outDir, 'index.html'))
console.log(`[review] wrote ${join(outDir, 'review.js')}`)

// The HTML carries the bundle inline, so the page is ONE self-contained file.
//
// Not a style choice: an ES module loaded with <script type="module" src="..."> is fetched with CORS,
// and a `file://` page has a null origin, so Chrome blocks it and the page renders blank while the
// file itself looks fine. An *inline* module script is not fetched, so it runs. That is also what
// makes the artifact openable by double-click and inside the JetBrains JCEF webview, which is the
// whole point of a local review display (DEC-027's "one self-contained file" for a report page).
const bundle = readFileSync(join(outDir, 'review.js'), 'utf8')
// The inlined copy drops the map reference: a comment pointing at `review.js.map` is a reference to a
// second file, and "one self-contained HTML" has to mean exactly that. The external review.js keeps it,
// so debugging the bundle still works.
const inlinedBundle = bundle.replace(/\n?\/\/# sourceMappingURL=.*\n?$/, '\n')
if (inlinedBundle.includes('</script')) {
  // Would close the inline script tag early. Nothing in this page should contain it; fail loudly
  // rather than emit a page that silently truncates.
  console.error('[review] the bundle contains "</script" and cannot be inlined safely')
  process.exit(1)
}
const html = readFileSync(join(packageRoot, 'index.html'), 'utf8')
const inlined = html.replace(
  '<script type="module" src="./review.js"></script>',
  `<script type="module">\n${inlinedBundle}\n</script>`,
)
if (inlined === html) {
  console.error('[review] index.html has no <script type="module" src="./review.js"> to replace')
  process.exit(1)
}
writeFileSync(join(outDir, 'index.html'), inlined)
console.log(`[review] wrote ${join(outDir, 'index.html')} (bundle inlined, self-contained)`)
