package hr.hrg.jetbrains.webview.toolWindow;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Whether a URL the tool window remembers is still worth loading.
 *
 * <p>The plugin remembers the last URL per project, which is a convenience — and a convenience is not a promise: the
 * file it named may have moved, been generated by a tool that is gone, or never existed in this checkout at all. The
 * repository's own kit examples moved into {@code webview/kit/examples/}, and the tool window kept restoring the old
 * path on every open, showing an error page for a file that no longer existed and looking broken.
 *
 * <p>So a remembered local URL is checked before it is used. Anything that is not a local file — an HTTP page, a
 * {@code data:} splash, whatever a future version serves — is left alone, because there is nothing to check and
 * guessing would be worse than loading it.
 *
 * <p>Pure on purpose: no project, no services, no browser, so the rule can be tested directly.
 */
public final class LocalFileUrls {

    private LocalFileUrls() {
    }

    /**
     * The local path a {@code file:} URL names.
     *
     * @return the path, or null when this is not a local file URL at all
     */
    public static @Nullable Path pathOf(@Nullable String url) {
        if (url == null || url.isBlank()) {
            return null;
        }
        String trimmed = url.trim();
        if (!trimmed.regionMatches(true, 0, "file:", 0, "file:".length())) {
            return null;
        }
        String raw = trimmed.substring("file:".length());
        try {
            // A URL, not a string: '%20' in a path is a space, and a Windows drive letter needs its leading slash
            // removed before it is a path again - the reverse of what the action's urlFor(...) writes.
            String path = URI.create(trimmed).getPath();
            if (path == null || path.isBlank()) {
                path = raw;
            }
            path = path.replaceFirst("^/+", "");
            return path.isBlank() ? null : Path.of(path);
        } catch (RuntimeException malformed) {
            // A URL we cannot parse is not one we can call missing; the browser will report it.
            return null;
        }
    }

    /**
     * True when the URL names a local file that is not there any more.
     *
     * <p>{@code false} for everything that cannot be checked — an HTTP URL, a {@code data:} URL, an unparseable one —
     * because forgetting a page we could have shown is worse than letting the browser try.
     */
    public static boolean missing(@Nullable String url) {
        Path path = pathOf(url);
        return path != null && !Files.isRegularFile(path);
    }

    /** The URL to remember, or an empty string when this one should be forgotten. */
    public static @NotNull String remember(@Nullable String url) {
        if (url == null || url.isBlank() || missing(url)) {
            return "";
        }
        return url;
    }
}
