<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>hr.hrg.watch2</groupId>
        <artifactId>java_watch2-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jwa-builder</artifactId>
    <name>JWA Builder</name>
    <description>Component for processing and generating Record builders</description>

    <dependencies>
        <dependency>
            <groupId>hr.hrg.watch2</groupId>
            <artifactId>jwa-builder-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-core</artifactId>
        </dependency>
        <dependency>
            <groupId>hr.hrg.watch2</groupId>
            <artifactId>java-watch-core</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
